Yoast/yoast-test-helper

src/WordPress_Plugin_Features.php
src/WordPress_Plugin_Version_Control.php

Fixes WPCS checks (and adds some very required security :) )

Add nonce checks

---

src/Admin_Page.php
src/Plugin.php
src/Post_Types.php
src/Taxonomies.php

Adds a setting to enable/disable post types and taxonomies, refactors how we do `get_controls`.

Add a setting for the post types

---

assets/css/admin.css
src/Admin_Page.php
src/Plugin.php
src/WordPress_Plugin_Version_Control.php
src/XML_Sitemaps.php

Allows disabling the XML sitemaps cache, just that, for now.
Also slightly changes the admin design, screenshot below.
Fixes #8

Add XML sitemaps class

---

src/Admin_Page.php
src/WordPress_Plugin_Features.php
src/WordPress_Plugin_Version_Control.php

Also use tools.php for feature reset and version control.
Make sure that notifications are not overlapped by other blocks.

Fix admin urls

---

src/Form_Presenter.php
src/Plugin_Toggler.php
src/Post_Types.php
src/WordPress_Plugin_Features.php
src/WordPress_Plugin_Version_Control.php
src/XML_Sitemaps.php

Introduce Form Presenter

---

.travis.yml

fixed repo slug

---

.travis.yml

test the build stage on a separate branch

Test stage

---

src/Feature_Toggler.php
src/Plugin.php
yoast-test-helper.php

Adds a feature toggler for the improved internal linking feature and any possible future feature flags we have.

Add Feature Toggler and only load autoloader if it exists

---

yarn.lock

Adds the latest version of the `yarn.lock` file.

Add latest build of the yarn.lock file

---

src/Feature_Toggler.php
src/Schema.php

* Fixes an issue where the schema `is_needed` filters would be activated on a fresh install.
* When the DB value is not equal to `none` it would add the filter. Now it removes the filter on receiving any other value than `show` or `hide`. Might be better to just remove on `none`, but this seems safer. What do you think?
* Some unrelated PHP CS fixes included too.
* Either have a fresh WordPress install OR ensure your database does not have the following:
- table `wp_option`
- option_name `yoast_test_helper`
- value: `is_needed_breadcrumb` and `is_needed_webpage`
* Open a post in the frontend, look at the schema json+ld output.
* Ensure it does have the webpage and breadcrumb …

Fix schema filter defaults

---

src/Feature_Toggler.php

* [n/a]
* Fixing some PHPCS errors that were introduced in an earlier PR>
* Check out this branch and run `vendor/bin/phpcs`. Confirm that there are no PHPCS errors.
* Use this plugin together with the `feature/internal-linking` branch on both premium and the javascript monorepo. Confirm that toggling internal linking on and off still works.
Fixes #

Fix PHPCS errors

---

Gruntfile.js
grunt/config/aliases.yaml
grunt/config/wp_deploy.js

- Adds a svnCheckoutDir
- Fixes the deploy script by using the correct names.

Fix deploy script

---

src/Option.php

This prevents a query in your query log.

Make plugin option autoload

---

src/schema.php

* Fixes a bug where the influence schema setting wouldn't save properly.

Fix schema save bug

---

composer.json
composer.lock

Composer: minor tidying up

---

src/admin-notifications.php
src/plugin-version-control.php
src/wordpress-plugins/yoast-seo.php
src/xml-sitemaps.php

* _N/A_
* Remove redundant and outdated whitelist comment.
* Simplify some PHPCS whitelist comments.
* Document the reason for use of a whitelist comment.
* _N/A_ If the build passes, we're good.

CS: tweaks PHPCS whitelist comments

---

src/plugin-toggler.php

* Minor housekeeping
*
* _N/A_ No functional changes,

CS: remove unused variable

---

src/plugin-version-control.php
src/post-types.php
src/schema.php
src/wordpress-plugin-features.php
src/wordpress-plugin-options.php

* Code style consistency
*
* _N/A_ No functional changes.

CS: minor whitespace fixes

---

src/admin-page.php
src/domain-dropdown.php
src/inline-script.php
src/plugin-toggler.php
src/schema.php
src/wordpress-plugins/local-seo.php
src/wordpress-plugins/video-seo.php
src/wordpress-plugins/yoast-seo.php
src/xml-sitemaps.php

* Minor performance improvement
*
* _N/A_

QA: use FQN constants in namespaced files

---

src/admin-page.php

Fix whitespace indentation ... and make Travis happy again.
* _N/A_ (no functional changes)

CS: fix whitespace

---

src/plugin-toggler.php

This generally makes for a smaller diff if something changes and improves readability.
* _N/A_ (no functional changes)

CS: boolean operator at the start of the line in multi-line conditions

---

src/admin-notifications.php
src/plugin.php

* Minor CS tweaks
* No import `use` statements for the same namespace.
* Use FQN function calls.
* No FQN in docblocks.
* _N/A_

CS: minor tweaks

---

src/wordpress-plugins/video-seo.php
src/wordpress-plugins/woocommerce-seo.php

* Fix the DB versions keys the plugin checks for Video SEO and WooCommerce SEO as they've been changed in these plugins.
Fixes QAK-1884

Fix DB version keys

---

readme.txt

* Set tested up to WP version to 5.5
*
*
Fixes #

Set tested up to WP version to 5.5

---

src/admin-page.php

* Fixes a bug where a deprecated jQuery function was used.
* used an upgrade path recommended by jQuery to replace a deprecated jQuery method call
* On `trunk`
* Install the `Enable jQuery Migrate Helper` plugin made by WordPress
* Navigate to the test helper page and see an error is given
* Checkout this branch
* See that the test helper isn't given an error.
* Merge 
*
Fixes #

Pass callback to the jQuery method

---

.travis.yml

* Replaces an archived vulnerability checker with the newer recommended package.
*
*
*
Fixes #

replace security checker

---

src/admin-bar-panel.php
src/admin-debug-info.php
src/admin-notifications.php
src/admin-page.php
src/domain-dropdown.php
src/feature-toggler.php
src/indexing-reason-integration.php
src/inline-script.php
src/plugin-version-control.php
src/support-session.php
src/wordpress-plugin-features.php
src/wordpress-plugins/yoast-seo.php

... for global functions and constants.
Similar to `extract()`, `compact()` can obscure what it happening.
Especially with a small array like this, might as well be explicit.
* _N/A_ This PR does not contain any functional changes.

CS: minor clean up after merges

---

src/plugin.php
src/query-monitor-output.php
src/query-monitor.php

* Fixes query monitor integration.
*
* Visit a front-end page.
* Open de query monitor tab.
* Click `Yoast SEO` in the query monitor to inspect the current page's indexable.
*
Fixes #

Fix query monitor integration

---

composer.lock

* Updated dev dependencies
* PHP_CodeSniffer from 3.6.0 to 3.6.1 for improved compatibility with code using attributes.
Refs:
* https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.1
* _N/A_

Composer: update dev dependencies

---

.github/workflows/deploy.yml

* Update CI
The `setup-node` action has released a new major.
This upgrades the deploy workflow to use this new action runner.
Ref: https://github.com/actions/setup-node/releases/tag/v3.0.0
* _N/a_ If the build passes, we're good.

GH Actions: update setup-node action runner
