Yoast/yoast-test-helper

assets/js/yoast-toggle.js
The `window.history.go` stuff didn't work properly on Safari. This does. Please test it in Chrome.
=> Switch how we reload the window

src/Admin_Debug_Info.php, src/Yoast_SEO_Admin_Bar_Debug_Panel.php
This moves the options display for Yoast SEO from underneath the settings screens to a debug bar panel which is always visible.
=> Try a debug bar panel

.travis.yml, scripts/deploy_to_dist.sh
*  automatically commit all files from a tagged commit to the dist repo
* Using Travis to automatically commit all files from a tagged commit to the dist repo
* Creating a tagged commit, pushing it to the GitHub remote and verifying if the files are in the distribution git 
Fixes #16
=> Automatically commit all files from a tagged commit to the dist repo

src/Admin_Debug_Info.php
Don't break when debug bar integration is active, yet Yoast SEO is inactive.
=> Fixes issue when Yoast SEO is inactive

src/WordPress_Plugins/Yoast_SEO.php
Restores muted and dismissed notifications.
Clears the notifications list, to make sure all remained notifications from disabled plugins are cleaned up.
Note: this does not force the "attachment URL" notification, as that is specific to certain settings.
=> Resets all notifications

src/WordPress_Plugins/Yoast_SEO.php
This is to remove the site information cache. The WPSEO_Addon_Manager uses this to check whether addon licenses are active or not. Normally this cache has a lifespan of 1 day.
I'm not sure how long this will be handy for. Since the normal ignoring of this on the Yoast SEO Premium page and probably the Yoast SEO Dashboard should be re-implemented.
=> Add an option to reset the site information

assets/js/yoast-toggle.js, src/Plugin_Toggler.php
Due to my habit of adding releases to the plugins directory. I was hoping to extend this plugin to include them in the toggle menu.
I found out this toggles between two in a namespace. I did not want to write a separate plugin to extend the array every time. So instead it now scans all the plugins and filters them by name and groups them by the regex groups.
There can now be more than 2 plugins per group. Still only 1 active plugin per group.
**Plugins folder**
**The toggle menu**
- Initializes the plugins array with WordPress's `get_plugins` filtered by name and grouped according to the regex.
- Added the filter `yoast_plugin_toggler_filter` to alter the `grouped_name_filter` regex.
- Implemented support for more than 2 plugins per group.
Have multiple plugins that start with `Yoast SEO` …
=> Add groups to plugin toggler

src/Plugin.php, src/Schema.php
Adds an option to replace your test domain name with `example.com` in JSON output. Prevents Google's Structured Data Testing Tool from throwing errors because your domain name is invalid for `.test` domains.
Relies on https://github.com/Yoast/wordpress-seo/pull/12537 being merged too.
=> Add Schema debug feature

phpcs.xml.dist, src/Form_Presenter.php, src/Plugin_Toggler.php, src/Schema.php, src/WordPress_Plugins/Yoast_SEO.php
* Added filters for the Breadcrumb and WebPage Graphs.
* Added selection creation helper.
* 3 choices: `Don't influence`, `Always include` and `Never include`.
* Switch to this branch.
* Activate the plugin in WP.
* Go to the `Tools -> Yoast Test` page.
* Go to a WP output post/page/whatever, open the source and copy the JSON+LD script.
* [Use Google's SDTT](https://search.google.com/structured-data/testing-tool/u/0/) to test the _stitching_.
* Try different values and check if the schema output matches.
* `Don't influence` should result in the same output as without the plugin installed.
* `Always include` is a bit harder to verify with some options. But you can go to `SEO -> …
=> Add schema filters

src/Form_Presenter.php, src/WordPress_Plugin_Features.php
* Adds IDs to the buttons.
* Using the nonce field as name since those make sense already. Then adding `_save` suffix for the forms and `_button` in the features.
* Check if the save buttons have valid IDs that end with `_save`.
* Check if the reset buttons have valid IDs that end with `_button`.
* Check if the buttons still work.
Fixes #
=> Add IDs to the buttons

package.json, yarn.lock
Test instructions:
Run `grunt artifact`.
Install the plugin as a zip `(archive.zip)` and make sure it works.
Fixes #38
=> Upgraded grunt-contrib-compress in order to upgrade tar-fs

yarn.lock
Upgrades tar to 2.2.2 and fstream to 1.0.12.
I ran `yarn upgrade grunt-contrib-compress`. Because there was no newer version, it updated grunt-contrib-compress's dependencies and dependecies of dependencies. Fstream and tar were two  of them.
* Run `grunt artifact` and see no errors. 
* Upload the artifact.zip as a plugin to your local installation.
* Activate the plugin and see that it works.
Fixes #47
Fixes #48
=> Upgrade fstream and tar

src/WordPress_Plugins/Yoast_SEO.php
Tracking is fired every two weeks. Adds a button to the Yoast Test Helper to reset the option thus triggering another tracking request.
=> Allow resetting the tracking

src/Admin_Page.php, src/Domain_Dropdown.php, src/Plugin.php, src/WordPress_Plugins/Yoast_SEO.php
Fixes #50 
Adds a dropdown to the test helper to set the testing domain for myYoast. When set, any call to myYoast will be replaced with the myYoast testing domain (for example: staging). 
* Redirect code based on this piece from jetpack: https://github.com/Automattic/jetpack/blob/792b26b5539d07cc35fdd93567942f2ad481eef2/_inc/jetpack-server-sandbox.php#L63
This PR can be tested by following these steps (happy-path):
1. Make sure you test this as a logged out user in an incognito window (if applicable).
1. Git clone the yoast-test-helper into your favorite yoast.com testing enviroment. The plugin directory should be here: `yoast.com/site/web/app/plugins/`
1. From that same directory run `rm -rf test-helper` to delete the test-helper that was preinstalled. 
1. In the cloned test helper …
=> Add option to set myYoast testing domain in the test helper.

src/WordPress_Plugin_Version_Control.php
* N/A
* 
1. Get the Yoast Test Helper plugin
1. Go to `Tools` > `Yoast Test` and try to type `10.0-RC0` as `DB Version` for `Yoast SEO` 
1. See that this is not possible (not able to type more than `10.0-RC`)
1. Checkout this branch
1. Go to `Tools` > `Yoast Test` and try to type `10.0-RC0` as `DB Version` for `Yoast SEO` 
1. See that this is now possible
Fixes #53
=> Change number of characters DB version #53

assets/css/admin.css, src/Inline_Script.php, src/Plugin.php
@dariaknl Needed an easy way to test javascript hooks.
This PR adds the following to the yoast test helper page:
Test instuctions:
- You can mimic the above settings to see the duration text filter be applied in the gutenberg how-to block.
```
// Adds a duration text filter to the how to block.
alert( "Reminder: Yoast Test Helper adds an inline script." );
window.wp.hooks.addFilter( "wpseo_duration_text", "my-awesome-plugin", () => {
console.log( "Filter called" );
return "Random3";
} );
```
- Open gutenberg, add an how to block and click `Add duration`.
- `Time needed:` Should be replaced with `Random3`.
=> Allow an inline script to be injected after a specified wpseo script.

src/Development_Mode.php, src/Plugin.php
When turned on, this filters `yoast_seo_development_mode` to `true`, which means every call to `WPSEO_Utils::is_development_mode` will return true and thus enables development mode.
=> Add Development mode toggle

src/Plugin.php, src/Upgrade_Detector.php, src/WordPress_Plugin_Version.php, src/WordPress_Plugin_Version_Control.php, src/WordPress_Plugins/Yoast_SEO_Premium.php
This adds the option to set the Yoast SEO Premium database version, and thus the option to make the upgrade routine run. It also adds a notification when that upgrade routine has run.
Known caveats: this doesn't _actually_ know whether the premium upgrade routine has fired, since there's no hook in premium to test for this, so it fires when the option is updated, which happens after the upgrade routines run, hence this message:
Fixes #58
=> Allow running the Yoast SEO Premium upgrade routine

src/WordPress_Plugins/Yoast_SEO.php
* Added a button to reset the configuration wizard to its initial state.
* Click the button, see that you have a notification for the configuration wizard.
=> Add config wizard reset

src/wordpress-plugin-features.php, src/wordpress-plugins/yoast-seo.php
* Add a reset indexable migrations feature
* Have a site that runs on Yoast SEO master.
* Upgrade it to indexables, see the new tables in your database.
* Hit the new "Reset indexables tables & migrations" button in Yoast test helper, see those tables are gone.
=> Add a reset indexable migrations feature

.travis.yml
* Improve QA checking
Development has switched from `master` to `develop`, but the `develop` branch was not whitelisted in the Travis script, so PRs would not be build.
Includes some additional tweaks:
* Remove `sudo: false`: Travis removed support for `sudo` nearly a year ago.
* Remove two conditions which would always be `false` as the PHPCS build is against PHP 7.4/latest stable.
* Use the `check-cs` Composer script for running PHPCS.
* Check that Travis is reporting back on this PR in the merge block and that the build passes.
=> Travis: run builds for PRs

src/admin-page.php, src/plugin-version-control.php, src/plugin.php, src/wordpress-plugin-features.php
* Code consistency.
Declare closures which don't use `$this` as `static` for a tiny performance improvement.
* _N/A_ No functional changes. Everything should still work the same as before.
=> QA: declare static closures as static

src/admin-debug-info.php, src/admin-notifications.php, src/admin-page.php, src/development-mode.php, src/domain-dropdown.php, src/feature-toggler.php, src/inline-script.php, src/plugin-toggler.php, src/plugin-version-control.php, src/plugin.php, src/post-types.php, src/schema.php, src/taxonomies.php, src/upgrade-detector.php, src/wordpress-plugin-features.php, src/wordpress-plugin-options.php, src/wordpress-plugin-version.php, src/wordpress-plugins/local-seo.php, src/wordpress-plugins/news-seo.php, src/wordpress-plugins/video-seo.php, src/wordpress-plugins/woocommerce-seo.php, src/wordpress-plugins/wordpress-plugin-interface.php, src/wordpress-plugins/yoast-seo-premium.php, src/wordpress-plugins/yoast-seo.php, src/xml-sitemaps.php
* Improve documentation
* Docs: fix param tag alignment
* Docs: annotate code in documentation as such
* Docs: fix return tag
PHP has no concept of named return variables, so the name of the variable has no value in the `@return` tag.
* Docs: fix typo
* Docs: improve specificity
... of array var/param/return types.
* Docs: use FQN in docblocks 
* _N/A_
=> Docs: various fixes

src/admin-bar-panel.php, src/admin-debug-info.php, src/admin-notifications.php, src/admin-page.php, src/development-mode.php, src/domain-dropdown.php, src/feature-toggler.php, src/inline-script.php, src/plugin-toggler.php, src/plugin-version-control.php, src/plugin.php, src/post-types.php, src/schema.php, src/taxonomies.php, src/upgrade-detector.php, src/wordpress-plugin-features.php, src/wordpress-plugin-options.php, src/wordpress-plugin-version.php, src/wordpress-plugins/local-seo.php, src/wordpress-plugins/news-seo.php, src/wordpress-plugins/video-seo.php, src/wordpress-plugins/woocommerce-seo.php, src/wordpress-plugins/yoast-seo-premium.php, src/wordpress-plugins/yoast-seo.php, src/xml-sitemaps.php
Always be explicit about which classes are being used in a namespaced file, even when it's a class from within the same namespace.
Using `ClassName::class` (PHP 5.5+) translates to the Fully Qualified Class name as a string.
* _N/A_ No functional changes.
=> QA: add missing import `use` statements for classes

src/admin-bar-panel.php, src/admin-debug-info.php, src/admin-notifications.php, src/admin-page.php, src/development-mode.php, src/domain-dropdown.php, src/feature-toggler.php, src/form-presenter.php, src/inline-script.php, src/option.php, src/plugin-toggler.php, src/plugin-version-control.php, src/plugin.php, src/post-types.php, src/schema.php, src/taxonomies.php, src/upgrade-detector.php, src/wordpress-plugin-features.php, src/wordpress-plugin-options.php, src/wordpress-plugin-version.php, src/wordpress-plugins/local-seo.php, src/wordpress-plugins/news-seo.php, src/wordpress-plugins/video-seo.php, src/wordpress-plugins/woocommerce-seo.php, src/wordpress-plugins/yoast-seo-premium.php, src/wordpress-plugins/yoast-seo.php, src/xml-sitemaps.php
* Minor performance improvements.
Using fully qualified names means that PHP won't have to look for the function in the current namespace before falling back to the global namespace, which gives a tiny performance boost for most functions and a larger one for a select list of PHP native functions using the OpCode cache (but only when at compile time it is clear that these function calls target the PHP native function).
* _N/A_ No functional changes. All should still work as before.
=> QA: use FQN function calls in namespaced files

src/admin-bar-panel.php, src/admin-debug-info.php
* Fix fatal error when used in combination with the Debug Bar plugin.
The class `Yoast\WP\Test_Helper\WPSEO_Options` does not exist. To use the Yoast SEO Free `WPSEO_Options` class, it needs to be imported via a `use` statement or the name must be fully qualified inline.
Along the same lines, the `Admin_Bar_Panel` is a namespace local class, not a global one from the Debug Bar plugin.
* While on `develop`, install & activate the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin.
* See a fatal error on any page.
* Switch to this branch and see that the fatal error no longer occurs.
=> Bug fix: fix fatal error / Debug bar panel

.gitignore, phpcs.xml.dist, yoast-test-helper.php
* Improved QA checks
Follow up to PR #64 which addresses the remaining open points as per https://github.com/Yoast/yoast-test-helper/pull/64#issuecomment-608294316
@jdevalk There's nothing very exiting about this PR, but as it's a follow-up to your earlier PR I figured I'd tag you.
For the ruleset: it'll be easiest to review the changes with the "ignore whitespace changes" option turned on.
* Add the `text_domain` property for the `I18n` sniff.
* Explicitly exclude the main file from the strict file name check.
* Enable parallel scanning for faster results.
Additionally:
* Add the XSD schema tags.
* Add inline documentation.
* Consistently use tab-indentation.
The global variable and the global constants declared in the …
=> PHPCS ruleset: iterate, add documentation and more

src/admin-debug-info.php, src/admin-notifications.php, src/development-mode.php, src/domain-dropdown.php, src/feature-toggler.php, src/inline-script.php, src/plugin-toggler.php, src/plugin-version-control.php, src/plugin.php, src/post-types.php, src/schema.php, src/taxonomies.php, src/wordpress-plugin-features.php, src/wordpress-plugin-options.php, src/wordpress-plugin-version.php, src/xml-sitemaps.php
Use unqualified names instead and if it involves a class from another namespace and no `use` statement is in place yet, add an import `use` statement.
* _N/A_ (no functional changes)
=> CS: revert "use FQN in docblocks"

src/admin-debug-info.php, src/admin-notifications.php, src/admin-page.php, src/development-mode.php, src/domain-dropdown.php, src/feature-toggler.php, src/inline-script.php, src/plugin-toggler.php, src/plugin-version-control.php, src/plugin.php, src/post-types.php, src/schema.php, src/taxonomies.php, src/upgrade-detector.php, src/wordpress-plugin-features.php, src/wordpress-plugins/local-seo.php, src/wordpress-plugins/news-seo.php, src/wordpress-plugins/video-seo.php, src/wordpress-plugins/woocommerce-seo.php, src/wordpress-plugins/yoast-seo-premium.php, src/wordpress-plugins/yoast-seo.php, src/xml-sitemaps.php
Import `use` statements for classes in the same namespace will not be allowed. This was decided yesterday in contrast to before.
* _N/A_ (no functional changes)
=> CS: partially revert "always use `use` statements"

src/wordpress-plugins/yoast-seo.php
* Drops the table for prominent words (used by our internal linking functionality, among others) when you drop the indexables tables.
* Added `IF EXISTS` checks to all the table drops.
* Run the [internal linking feature branch](https://github.com/Yoast/wordpress-seo/tree/feature/internal-linking-phase-2).
* See the `yoast_prominent_words` table gets created, drop it using the button.
Fixes #91
=> Drop table for prominent words

src/wordpress-plugins/yoast-seo.php
* Resets the new improved prominent words integration.
*
* On premium make sure the prominent words are calculated. 
* Press the button to reset the prominent words calculation
* Verify that the prominent words table is emptied and that all prominent_words_version values in the indexables tables are set to null
Fixes #95
=> Add logic to reset the prominent words

src/wordpress-plugins/yoast-seo.php
* Updates the reset_configuration_wizard function according to the changes in https://github.com/Yoast/wordpress-seo/pull/14917
IMPORTANT NOTICE
This should only be merged after https://github.com/Yoast/wordpress-seo/pull/14917 is merged into admin-redesign and that that branch is merged into trunk.
* The WPSEO_Options option called started_configuration_wizard is reset to false in the newly updated method.
* Checkout the branch of [#14800](https://github.com/Yoast/wordpress-seo/pull/14917) and build
* Reset the configuration wizard in the helper
* Go to the yoast SEO dashboard and refresh
* There should be a notification which tells you to start the configuration wizard, click that …
=> Update reset configuration wizard function

.cache/.gitkeep, .gitattributes, .gitignore, .travis.yml, phpcs.xml.dist
* Enable caching for PHPCS
Since PHPCS 3.0.0, PHPCS has a caching feature available. In this PR, this caching feature is now turned on for this repo.
This means in effect that the very first run of PHPCS with this feature will be marginally slower (on any individual machine). Most runs _after_ that though, will be significantly faster as PHPCS will only scan the files which have changed since the previous run.
The cache will automatically be invalidated and rebuild whenever relevant, like when the version of one of the PHPCS dependencies has changed or when PHPCS itself has been changed.
To (temporarily) turn caching off, run PHPCS like so:
```bash
composer check-cs -- --no-cache
```
The cache file is set to be saved to a …
=> PHPCS: enable caching between runs

src/wordpress-plugins/yoast-seo.php
* Added resets for indexables related options upon using Yoast Test Helper to reset the indexables and migrations.
* Also includes the deletion of transients from https://github.com/Yoast/wordpress-seo/pull/15362.
Make sure you are on the 14.5 build of Yoast SEO.
If https://github.com/Yoast/wordpress-seo/pull/15362 hasn't been merged yet, check out that branch instead.
* Make sure all indexables have been indexed under `Yoast SEO` > `Tools`.
* Reset the indexables using this plugin.
* Check that the following options have been set to `false` in the `wpseo` option in the `wp_options` table: `ignore_indexation_warning`, `indexation_warning_hide_until`, `indexation_started`, …
=> Reset indexables options upon resetting indexables

src/form-presenter.php, src/schema.php
* Adds a checkbox to set and unset the feature flag for the structured data blocks.
* I basically copied the implementation from the other checkbox in the Schema section of the Test Helper ("Replace .test domain name with example.com in Schema output.").
* This explains why `wpseo_debug_json_data` is the filter that I'm hooking into.
* Open the Test Helper.
* In the Schema section, see a checkbox: "Enable the feature flag for the structured data blocks.".
* Check the box and save.
* In your database, in `wp_options`, in `yoast_test_helper`, see that `enable_structured_data_blocks` has been set to `1`.
* As long as [the PR](https://yoast.atlassian.net/browse/P2-342) that implements …
=> Add a checkbox for the structured data feature flag

package.json, readme.txt, src/wordpress-plugins/yoast-seo.php, yoast-test-helper.php
* Fixes a bug where the old links table is reset resulting in the link columns not being emptied.
* Fixes a bug where the links could be attached to the wrong indexables when resetting the indexable tables and migrations.
* Chosen to also remove the links table because it is coupled with the indexables and thus is more or less an indexables feature.
ZIP file of 1.9-RC1 for testing:
[yoast-test-helper-1.9-RC1.zip](https://github.com/Yoast/yoast-test-helper/files/5312044/yoast-test-helper-1.9-RC1.zip)
* Have everything indexed.
* Reset the link counts and see in the post overview that the link counts are resetted.
* Have the links calculated and make sure the `wp_yoast_seo_links` …
=> Fix resetting the link counter

src/wordpress-plugins/yoast-seo.php
* Removes a cron-job that checks the indexables daily when resetting the indexables.
* Resets the `indexing_first_time` option when resetting the indexables.
*
* Run the indexation on the Yoast -> Tools page.
* Reset the indexables.
* Make sure the `Start SEO Data optimization` button is back.
Fixes #
=> Remove cron job when resetting indexables

.travis.yml
* Prepare for the release of PHP 8
While this plugin doesn't have any (unit) tests, let's at least lint the plugin files against PHP 8.
* Check the output of the Travis build for the PR.
=> Travis: lint files against PHP 8

composer.json, composer.lock
* Updated dev dependencies
* Updated YoastCS from `2.0.2` to `2.1.0`.
* Updated PHP_CodeSniffer from `3.5.5` to `3.5.8`.
* Updated the DealerDirect Composer plugin from `0.6.2` to `0.7.0` (which is compatible with Composer 2.0).
Relevant changes in YoastCS:
* The minimum supported WP version has changed to `5.4`.
* A new check for test doubles being named as such.
* A few bugfixes.
* Various sniffs now provide metrics.
Relevant changes in PHPCS:
* PHPCS will now _run_ without problems on PHP 8.
Note: it will not necessarily handle all code using PHP 8 syntax correctly yet, though it does contain preliminary support for various syntaxes.
* Lots of bugfixes.
Refs:
* https://github.com/Yoast/yoastcs/releases/tag/2.1.0
* …
=> Composer: update YoastCS to v 2.1.0

.travis.yml, src/wordpress-plugins/yoast-seo.php
* Uses the new option name for resetting these options, and removes the setting of two other options which are no longer used.
* This PR accompanies https://github.com/Yoast/wordpress-seo/pull/16239.
* When this PR has been merged, the Test Helper will require Yoast SEO 15.3 (or higher) for the indexable resetting functionality to work.
**Test setting the Free options**
* Activate Free.
* Make sure that Yoast SEO has the code from https://github.com/Yoast/wordpress-seo/pull/16239.
* Run the indexing process on the Yoast Tools page (if you hadn't already).
* Reset the indexables in the test helper.
* In your database, in `wp_options` --> `wpseo`, see the following key-value pairs:
* …
=> Rename options and remove old ones

src/indexing-reason-integration.php, src/indexing-reason.php, src/plugin.php, src/wordpress-plugins/yoast-seo.php
* Fixes a bug where no notification is shown to reindex your site when resetting the indexables tables and migrations.
* Fixes a bug where no notification is shown to reindex your site when resetting the prominent words table.
* Fixes a bug where no notification is shown to reindex your site when resetting the internal link count.
* 
* Make sure that the Yoast Free or Premium plugin is activated.
* Make sure that your site is fully indexed.
* Reset the indexables table and migrations using the test helper.
* You should get a new notification in the Yoast SEO dashboard to reindex your site.
* Make sure that the Yoast Free or Premium plugin is activated.
* Make sure that your site is …
=> Show a notification when resetting the indexable tables, prominent words or internal link count.

src/wordpress-plugins/yoast-seo.php
* Fixes a bug where the `Reset indexables tables & migrations` functionality did not reset the internal link count transients.
* The `reset_indexables` method is meant to reset everything, including the internal link count and the prominent words calculation. However, `reset_indexables` was incomplete. For example, it didn't reset the transients related to the internal link count (`wpseo_unindexed_post_link_count` and `wpseo_unindexed_term_link_count`) and related to the prominent words calculation (`total_unindexed_prominent_words`). I decided to call `reset_prominent_words_calculation` and `reset_internal_link_count` from within `reset_indexables`, so that I didn't have to duplicate their code.
This PR can be acceptance tested …
=> Make reset functionality more robust

src/domain-dropdown.php
If the Host header remains "my.yoast.com", the request will go to the live servers even though the url says staging-my.yoast.com.
* Fixed a bug where all MyYoast requests would go to live my.yoast.com instead of the selected value of the domain dropdown.
1. Visit wp-admin/admin.php?page=wpseo_licenses on your test site. You activation status should say either "activated" or "not activated".
1. Go to my.yoast.com/sites and try to do the following:
* If the site was not activated, register your site with MyYoast and link your Yoast SEO for WP Premium license to that site.
* If the site was activated, see if you own the licence. If so, deactivate it. If not, proceed with …
=> Change the Host header along with the host in the url

src/wordpress-plugins/yoast-seo.php
* Adds the option to reset SEO roles & capabilities.
* Also resets premium-specific roles & capabilities.
* Install a plugin like User Role editor to change the capabilities of a role
* Any capability on an SEO specific role.
* SEO capabilities on any role.
* In the test helper click on the Reset roles & capabilities button.
* Your changes should be undone.
=> Add option to reset SEO roles & capabilities

composer.lock
* Update dev dependencies
Update various dev dependencies:
* DealerDirect Composer PHPCS plugin from v 0.7.0 to 0.7.1
* PHP Parallel Lint from v 1.2.0 to 1.3.0
* PHPCompatibilityWP from 2.1.0 to 2.1.1
* PHPCompatibilityParagonie from 1.3.0 to 1.3.1
* PHP_CodeSniffer from 3.5.8 to 3.6.0
Refs:
* https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.7.1
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.0
* https://github.com/PHPCompatibility/PHPCompatibilityWP/releases/tag/2.1.1
* https://github.com/PHPCompatibility/PHPCompatibilityParagonie/releases/tag/1.3.1
* https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.6.0
This PR can be acceptance tested by following these …
=> Composer: update dev dependencies

src/schema.php
... to prevent using a reserved keyword as a parameter name.
While this isn't forbidden, in PHP 8.0+ with named parameters this can lead to very confusing code, so better to use another name.
* _N/A_, this PR does not contain functional changes.
=> CS/QA: minor updates

src/plugin.php, src/query-monitor-output.php, src/query-monitor.php, src/yoast-querymonitor-output.php
* Add Indexable data to Query Monitor
See video:
https://user-images.githubusercontent.com/487629/122607814-7062a580-d07b-11eb-99a8-97753c803041.mp4
* Open Query Monitor, see the new Yoast SEO tab, see it has Indexables data.
=> Add Indexable data to Query Monitor

src/wordpress-plugins/yoast-seo.php
* Fixes a bug where not all the transients that hold unindexed counts were deleted when users hit the "Reset Indexables & Migrations" button.
* I searched in Free for all the `UNINDEXED_COUNT_TRANSIENT` and `UNINDEXED_LIMITED_COUNT_TRANSIENT` variables.
* I searched in Premium for these variables too (they didn't exist) but did find an unindexed count transient for prominent words in `content-action.php`.
_Context_
* You can find these transients in the `options` table in your database.
* Without this PR, the following transients aren't reset when you hit "Reset Indexables & Migrations":
* `wpseo_total_unindexed_posts_limited`
* `wpseo_total_unindexed_terms_limited`
* …
=> Add missing (limited) unindexed count transients to the indexable reset functionality

src/wordpress-plugins/yoast-seo.php
⚠️ Note: you can only use the Free button when you have `Yoast SEO` **activated** and you can only use the Premium button when you have both `Yoast SEO` **and** `Yoast SEO Premium` **activated**.
* Adds buttons to reset the Free and Premium installation success screens, such that on reactivating the plugins, the corresponding installation success screen is shown again.
*
* Activate Yoast SEO Free and Premium and the Yoast Test Helper.
* Navigate to Tools > Yoast Test
* Use the `Reset Free installation success page` button, see you get a success message
* In the database, check that `activation_redirect_timestamp_free` in `wpseo` has been set to '0'
* Use the `Reset …
=> Add buttons to reset the free and premium installation success pages

.github/workflows/deploy.yml
* Improve CI
By default the `actions/checkout` does a shallow clone. This means that other branches will not be known, so would always be created as new.
By setting `fetch-depth` to `0`, a complete clone will be made, including all tags and branches.
This will make the deploy slightly slower, but as the `dist` repos are nowhere near as huge as the `dev` repos, this should still be relatively limited.
If this at some point would become problematic, we can have a think about using a "sensible number" for `fetch-depth` (something like `1000` or so).
Note: this change isn't for the most part not needed for this repo as the repo only deploys on tags. However, it will still make the workflow more stable for those exceptional times when …
=> GH Actions: fix the deploy checkout

src/downgrader.php, src/plugin.php
* Adds a new tool to safely downgrade Yoast SEO, including reverting all run migrations and resetting the version number.
* Downgrading to below 14.1 is not supported as before that the migrations directory was in a different location.
* Enter a version number, ideally one with different migrations than the version you are running.
* Click save.
* You should now be at the version specified with only the migrations matching that version and your version number in the DB should also match.
=> Add downgrade tool

src/wordpress-plugins/yoast-seo.php
* Introduces buttons to reset the first-time configuration and the premium workouts.
* The resetting currently targets the first-time configuration as a workout, it will need to be updated in the future when it's moved/refactored in the internals
* The button resets only the state of the steps for the first-time configuration, not the content of the input boxes.
* Activate Yoast SEO Free and the Yoast Test Helper.
* Start the configuration workout and complete some steps (or complete the full workout)
* Navigate to Tools > Yoast Test
* Use the `Reset First-time configuration` button, see you get a success message
* Navigate again to the workouts page and see that the …
=> DUPP-146 reset first time configuration and premium workouts

readme.txt
* Set minimum WordPress version to 5.8 and tested up to version to 5.9.
* On January 25, 2022, WordPress 5.9 was released. We've decided to go back to supporting only the latest 2 WordPress versions.
*
*
Fixes #
=> Set minimum WP version to 5.8 and tested up to to 5.9

src/wordpress-plugins/yoast-seo.php
* Introduces buttons to reset the options and the cornerstone flags
* Deleting the post meta that flags cornerstone content is not enough to empty the cornerston workout: hte indexables need to be rebuilt. We chose to not perform a purge of indexables with the new button because it can be unexpected and undesired to users.
* I updated the "First time configuration" and "Premium workouts" labels adding "progress" to make it clearer that only progress is reset, not the content of the steps.
* Activate Yoast SEO Free and Premium and the Yoast Test Helper.
* Edit some options e.g. in Search Appearance and Social so they differ from the defaults
*  make sure to change some …
=> DUPP-284 Introduce button to reset options to defaults

src/downgrader.php
* Fixes an unreleased bug where the Yoast version would not updated in the db after a downgrade.
*
* Install and activate Yoast SEO 18.4 RC5.
* Install and activate Yoast Test Helper 1.16-RC1.
* Go to Test Helper → Downgrade Yoast SEO → enter 18.0 and click save.
* You see successful message.
* Check Plugins page - Yoast SEO is 18.0.
Without this PR:
* Check _options table in DB:wpseo still contains s:7:"version";s:8:"18.4-RC5";
Without this PR:
* Check _options table in DB:wpseo still contains s:7:"version";s:4:"18.0";
*
Fixes https://yoast.atlassian.net/browse/DUPP-351
=> Fix old version in "wpseo" option after downgrade via Yoast Test Helper

src/downgrader.php
* Fixes an unreleased bug where a wrong migrations version would be set in the DB after a downgrade.
*
* Install and activate Yoast SEO 18.4 RC5.
* Install and activate Yoast Test Helper 1.16-RC1.
* Go to Test Helper → Downgrade Yoast SEO → enter 18.0 and click save.
* You see successful message.
* Check _options table in DB: `yoast_migrations_free`  contains s:7:"version";s:4:"18.0";
*
Fixes #
=> Fix migration version

.github/workflows/cs.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/security.yml
* Update CI
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases
* _N/A_ If the build passes, we're good.
=> GH Actions: version update for various predefined actions

src/wordpress-plugins/yoast-seo.php
* Removes the obsolete `Reset Configuration Wizard` button.
*
* Go to Tools->Yoast Test
* Confirm that the Reset Configuration Wizard is no longer there
Also:
* Click a different button, maybe `Reset Options` and confirm it works as expected.
Fixes #
=> Remove Reset Configuration Wizard button
